# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Restore BuildKit state
        uses: isac322/buildkit-state@v2
        with:
          buildx-name: ${{ steps.buildx.outputs.name }}
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  # dvc:
  #    runs-on: windows-latest
  #    steps:
  #      - name: Checkout repository
  #        uses: actions/checkout@v4

  #      - name: Set up Python
  #        uses: actions/setup-python@v4
  #        with:
  #          python-version: 3.10.10

  #      - name: Install DVC
  #        run: pip install dvc[all]

  #      - name: Pull DVC Data
  #        run: |
  #          dvc pull --force && git commit -am "Update data" && git push 

  train:
    runs-on: windows-latest
  # needs: dvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10

      - name: Install dependencies
        run: pip install -r requirements.txt --no-deps

      - name: Run Training
        run: python src/train.py

  docker:
    runs-on: ubuntu-latest
    needs: 
      - train
      - buildx 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: username/project-name:latest
